# Generated by Django 4.2.2 on 2023-10-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='change',
        ),
    ]
